### ISSUE TITLE
Issue while executing custom vbs.

### ISSUE THREAD

**Issue by J0e-BLAck9988** [knight0x07/Lnk2Vbs#2]
I created a simple vbs file, that would display a simple msg box; Below is it's content-

```
Set objShell = CreateObject("WScript.Shell")

' Display a simple message box
MsgBox "Hello, World!", vbInformation + vbOKOnly, "Important"
```
Upon Execution-
------------------
The python script runs good, a .lnk file is generated but on clicking it desired output isn't produced.

Attaching ss for the same!

Desired Output-
![Screenshot 2024-01-05 121733](https://github.com/knight0x07/Lnk2Vbs/assets/155705655/7d0b80d8-5cad-42b5-a4e6-c3932596fbb2)

But on clicking generated lnk file this message box isn't displayed.

**Comment by knight0x07** [comment]
Yo
Remove the commented line "Display a simple message box" from the vbs and then generate the lnk file.
 It works perfectly! \m/

![image](https://github.com/knight0x07/Lnk2Vbs/assets/60843949/41e5d5dd-cd8f-42e6-b96b-3e98ad9946e5)

Thanks,
knight0x07

**Comment by J0e-BLAck9988** [comment]
Yes, I figured that out too. Anyways thanks for the help.
